[global]
output_dir=/home/username/fmg-cert-export

ignore_name=Fortinet_CA_SSL,Fortinet_Factory
ignore_comment=test,ignore

[FMG_PROD]
host=10.10.10.10
token=XXXXXXXXXXXXXXXXXXXXX
adom=Prod


[FMG_TEST]
host=10.10.10.10
token=YYYYYYYYYYYYYYYYYYYY
adom=Test
